# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{syncro}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex MacCaw"]
  s.date = %q{2010-02-05}
  s.description = %q{Sync Ruby classes between clients.}
  s.email = %q{info@eribium.org}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "lib/syncro.rb",
     "lib/syncro/app.rb",
     "lib/syncro/client.rb",
     "lib/syncro/protocol/message.rb",
     "lib/syncro/protocol/message_buffer.rb",
     "lib/syncro/response.rb",
     "lib/syncro/scribe_observer.rb",
     "lib/syncro/server.rb"
  ]
  s.homepage = %q{http://github.com/maccman/syncro}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Sync Ruby classes between clients.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_runtime_dependency(%q<scriber>, [">= 0.0.1"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<scriber>, [">= 0.0.1"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<scriber>, [">= 0.0.1"])
  end
end

